[General]
firstTime=false
windowMaximized=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\xba\0\0\x3\xca\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0\x45\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[AppSettings]
appMode=0
defaultJpgQuality=97
firstTime.nomacs.3=false

[CustomPluginShortcuts]
Composite%20Image=Composite Image
Crop%20to%20Metadata=Crop to Metadata
Crop%20to%20Page=Crop to Page
Draw%20to%20Page=Draw to Page
Fake%20Miniatures=Fake Miniatures
Image%20Transform=Image Transform
Paint%20on%20Image=Paint on Image

[DisplaySettings]
bgColorNoMacsRGBA=4294506744
bgColorWidgetRGBA=2281701376
fgColorNoMacsRGBA=4281545523
highlightColorRGBA=4278225151
iconColorRGBA=4281545523
stylePlugin=fusion

[DkAppManager]
Apps\1\appName=&文件管理器
Apps\1\appPath=OpenDir
Apps\1\objectName=OpenDir
Apps\2\appName=&默认应用
Apps\2\appPath=OpenFile
Apps\2\objectName=OpenFile
Apps\size=2

[DkDialog]
SavePluginChanges=true
SavePluginChanges-answer=65536

[DkExplorer]
Date%20ModifiedHidden=true
Date%20ModifiedSize=0
LoadSelected=false
NameHidden=false
NameSize=285
ReadOnly=true
SizeHidden=true
SizeSize=0
TypeHidden=true
TypeSize=0

[DkFilePreview]
windowPosition=1

[DkMetaDataHUD]
keyValues=File.文件名, File.路径, File.大小, Exif.Image.Make, Exif.Image.Model, Exif.Image.DateTime, Exif.Image.ImageDescription, Exif.Photo.UserComment, Exif.Photo.ISO, Exif.Photo.FocalLength, Exif.Photo.ExposureTime, Exif.Photo.Flash, Exif.Photo.FNumber
numColumns=-1
windowPosition=3

[DkPaintViewPort]
penColor=4278190080
penWidth=15

[GlobalSettings]
language=zh_CN
recentFolders=/home/pang/Pictures/Screenshots, /home/pang, /home/pang/Pictures/背景图片

[Page%20Extraction%20Plugin]
Method=0

[SynchronizeSettings]
checkForUpdates=true
disableUpdateInteraction=false

[zooming]
useLevels=false
zoomLevels="0.0001,0.001,0.01,0.05,0.1,0.125,0.166,0.25,0.333,0.5,0.66,1,1.5,2,3,4,5,6,7,8,12,16,32,64,128"
