[colors.primary]
background = '#1a1111'
foreground = '#f0dede'

[colors.selection]
text = '#f0dede'
background = '#723337'

[colors.cursor]
text = '#1a1111'
cursor = '#ffb3b5'

[colors.normal]
black   = '#1a1111'
red     = '#ff7273'
green   = '#9bff7f'
yellow  = '#ffe372'
blue    = '#f29b9d'
magenta = '#723337'
cyan    = '#ffb3b5'
white   = '#ffeff0'

[colors.bright]
black   = '#494041'
red     = '#ff9f9f'
green   = '#b9ffa5'
yellow  = '#ffeda5'
blue    = '#ffbec0'
magenta = '#ffc9cb'
cyan    = '#ffdcdd'
white   = '#fff8f9'
