[colors.primary]
background = '#101418'
foreground = '#e0e2e8'

[colors.selection]
text = '#e0e2e8'
background = '#164974'

[colors.cursor]
text = '#101418'
cursor = '#9ecafc'

[colors.normal]
black   = '#101418'
red     = '#ff729c'
green   = '#7efc8f'
yellow  = '#fff772'
blue    = '#84b6ef'
magenta = '#244a74'
cyan    = '#9ecafc'
white   = '#eff6ff'

[colors.bright]
black   = '#979da3'
red     = '#ff9fbb'
green   = '#a5ffb1'
yellow  = '#fffaa5'
blue    = '#aed3ff'
magenta = '#bcdbff'
cyan    = '#d4e8ff'
white   = '#f8fbff'
