cursor #f0dede
cursor_text_color #d7c1c1

foreground            #f0dede
background            #1a1111
selection_foreground  #44292a
selection_background  #e6bdbd
url_color             #ffb3b5

color0   #1a1111
color1   #ff7273
color2   #9bff7f
color3   #ffe372
color4   #f29b9d
color5   #723337
color6   #ffb3b5
color7   #ffeff0
color8   #494041
color9   #ff9f9f
color10  #b9ffa5
color11  #ffeda5
color12  #ffbec0
color13  #ffc9cb
color14  #ffdcdd
color15  #fff8f9
