cursor #e0e2e8
cursor_text_color #c2c7cf

foreground            #e0e2e8
background            #101418
selection_foreground  #243140
selection_background  #bac8db
url_color             #9ecafc

color0   #101418
color1   #ff729c
color2   #7efc8f
color3   #fff772
color4   #84b6ef
color5   #244a74
color6   #9ecafc
color7   #eff6ff
color8   #979da3
color9   #ff9fbb
color10  #a5ffb1
color11  #fffaa5
color12  #aed3ff
color13  #bcdbff
color14  #d4e8ff
color15  #f8fbff
